---
title: "R Day 2"
author: "Tony Colucci"
date: "9/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
here::here("data", "gapminder5.csv")

gapminder <- read.csv(here::here("data", "gapminder5.csv"))
```


## Converting factors to characters

```{r}
gapminder$country <- as.character(gapminder$country)
gapminder$continent <- as.character(gapminder$continent)
str(gapminder)
```

```{r}
obs <- 1:nrow(gapminder)

for (i in obs) {
  gapminder[i, "gdp"] <- gapminder[i, "pop"] * gapminder[i, "gdpPercap"]
}
```

```{r}
for (i in obs) {
  gapminder[i, "log_gdpPercap"] <- log(gapminder[i, "gdpPercap"])
  gapminder[i, "log_pop"] <- log(gapminder[i, "pop"[]])
}
```

```{r}
continents <- unique(gapminder$continent)
for (i in continents) {
  mean_leCont <- mean(gapminder$lifeExp[gapminder$continent == i],
                      na.rm = TRUE)
  print(paste0(i, " : ", mean_leCont))
}

```


```{r}
years <- unique(gapminder$year)
for (i in continents) {
  print(paste0("Continent : ", i))
  for (j in years) {
    sd_le <- sd(gapminder$lifeExp[gapminder$continent == i &
                                    gapminder$year == j])
    print(paste0(j, " : ", sd_le))
  }
}
```

```{r}
i <- 1987

while (i <= 2002) {
  sd_le <- sd(gapminder$lifeExp[gapminder$year == i])
  print(paste0(i," : ", sd_le))
  i <- i + 5
}
```

```{r}
for (i in years) {
  if (i >=1987) {
    tmp <- mean(gapminder$pop[gapminder$year == i], na.rm = TRUE)
    print(paste0(i, " : ", tmp))
  } else {
    print(paste0("Sorry ", i, " is before 1987"))
  }
}
```

```{r}
cont_life_exp_stats <-
  function(df, cont) {
    le_mean <- mean(df$lifeExp[df$continent ==  cont])
    le_median <- median(df$lifeExp[df$continent ==  cont])
    le_min <- min(df$lifeExp[df$continent ==  cont])
    le_max <- max(df$lifeExp[df$continent ==  cont])
    
    cat("Continent:", cont,
        "\nMinimum:", le_min,
        "\nMean", le_mean,
        "\nMedian", le_median,
        "\nMaximum", le_max)
  }

cont_life_exp_stats(gapminder, "Asia")
```

```{r}
anydata <-
  function (year) {if (any(gapminder$year == year)) {
    print(paste0("This data frame contains data from ", year))
  } else {
    print(paste0("This data frame does not contain any data from ", year))
  }
  }

anydata(2002)
anydata(2012)
```

```{r}
mean_low_le <-
  function(df) {
    countries <- unique(df$country)
    for (i in countries) {
      country_le <-mean(df$lifeExp[df$country == i])
      if (country_le < mean(df$lifeExp)) {
        print(paste0(i, " : ", country_le))
      }
    }
  }

mean_low_le(gapminder)
```

```{r}
class_cont_le <-
  function(df) {
    for (i in unique(df$continent)) {
      cont_le <- mean(df$lifeExp[df$continent == i])
      if (cont_le > 70) {
        print(paste0("The life expectancy in ", i, " is greater than 70"))
      } else if (cont_le > 50) {
        print(paste0("The life expectancy in ", i, " is between 50 and 70"))
      } else {
        print(paste0("The life expectancy in ", i, " is less than 50"))
      }
    }
  }

class_cont_le(gapminder)
```

```{r}
df_info <- 
  function(df) {
    sapply(df, class)
  }

df_info(gapminder)
```

```{r}
vec_info <-
  function(vec, includeMed = FALSE) {
    print(paste0("Mean: ", mean(vec)))
    print(paste0("Std. Dev.: ", sd(vec)))
    if (includeMed == TRUE) {
      print(paste0("Median: ", median(vec)))
    }
  }

v1 <- c(123412,241342,123213,32,12,3,123124)
vec_info(v1, TRUE)
```

```{r}
log_lm <-
  function(df, dv, iv, year) {
    ## First take the vector of log values for both our dependent and independent variables
    dv_year <- df[[dv]][df$year == year]
    iv_year <- df[[iv]][df$year == year]
    log_dv <- log(dv_year)
    log_iv <- log(iv_year)
    
    
    
    ## Now we can plot our log values to view the relationship
    plot(log_iv, log_dv)
  }

log_lm(gapminder, "gdpPercap", "lifeExp", 1987)
```

